### PR TITLE
Replace unicode characters with ascii in the README.

### PR DESCRIPTION
**Pull request by m00natic**
I'm trying to create minimal development/release environment on
dockerized CentOS and trying to quickload :weblocks from ultralisp
with sbcl(-bin) 1.4.14 run into this:

> ; Loading "weblocks"
> ...
> debugger invoked on a LOAD-SYSTEM-DEFINITION-ERROR in thread #<THREAD "main thread" RUNNING {10005205B3}>: Error while trying to load definition for system log4cl-json from pathname
> /root/.roswell/lisp/quicklisp/dists/ultralisp/software/40ants-log4cl-json-20181124183503/log4cl-json.asd: READ error during LOAD: :ASCII stream decoding error on #<SB-SYS:FD-STREAM for "file
> /root/.roswell/lisp/quicklisp/dists/ultralisp/software/40ants-log4cl-json-20181124183503/README.rst" {1006293323}>: the octet sequence #(226) cannot be decoded.(in form starting at line: 1,
> column: 0, position: 0)
> 
> Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
> ...

Replacing the unicode characters fixes it.  Maybe there's something
deeper and obviously that doesn't happen on "normal" machines but I
think it's worth it to get rid of these fancy characters.

### CODE REVIEW

**Comment by svetlyak40wt** [comment]
@m00natic thank you for this pull.

Could you please, show what does `locale` command line command show on your machine?

**Comment by svetlyak40wt** [comment]
By the way, on my machine I have:

```
[art@art-osx5:/tmp/check-weblocks-install]% locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

And everything work fine:

```
[art@art-osx5:/tmp/check-weblocks-install]% qlot exec ros run -L sbcl-bin --eval '(ql:quickload :log4cl-json)'
To load "log4cl-json":
  Load 1 ASDF system:
    log4cl-json
; Loading "log4cl-json"
......
*
```

But by settings `C` locale I was able to reproduce this problem:

```
[art@art-osx5:/tmp/check-weblocks-install]% LC_ALL=C qlot exec ros run -L sbcl-bin --eval '(ql:quickload :log4cl-json)'

debugger invoked on a LOAD-SYSTEM-DEFINITION-ERROR in thread #<THREAD "main thread" RUNNING {10005205B3}>: Error while trying to load definition for system log4cl-json from pathname /private/tmp/check-weblocks-install/quicklisp/dists/ultralisp/software/40ants-log4cl-json-20181124183503/log4cl-json.asd: READ error during LOAD: :ASCII stream decoding error on #<SB-SYS:FD-STREAM for "file /private/tmp/check-weblocks-install/quicklisp/dists/ultralisp/software/40ants-log4cl-json-20181124183503/README.rst" {10048DA4F3}>: the octet sequence #(226) cannot be decoded.(in form starting at line: 1, column: 0, position: 0)

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT                        ] Abort loading file "/private/tmp/check-weblocks-install/quicklisp/dists/ultralisp/software/40ants-log4cl-json-20181124183503/log4cl-json.asd".
  1: [RETRY                        ] Retry #<DEFINE-OP > on #<UNDEFINED-SYSTEM "log4cl-json">.
  2: [ACCEPT                       ] Continue, treating #<DEFINE-OP > on #<UNDEFINED-SYSTEM "log4cl-json"> as having been successful.
  3:                                 Retry ASDF operation.
  4: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
  5:                                 Retry ASDF operation.
  6:                                 Retry ASDF operation after resetting the configuration.
  7:                                 Give up on "log4cl-json"
  8: [CONTINUE                     ] Ignore runtime option --eval "(ros:run '((:eval\"(ros:asdf)\")(:eval\"(ros:quicklisp)\")(:eval \"(ql:quickload :log4cl-json)\")))".
  9:                                 Skip rest of --eval and --load options.
 10:                                 Skip to toplevel READ/EVAL/PRINT loop.
 11: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

((FLET "H0" :IN PERFORM) #<SB-C::INPUT-ERROR-IN-LOAD {10048DEF43}>)
; File has been modified since compilation:
;   /Users/art/.roswell/lisp/asdf/3.3.2.11/asdf.lisp
; Using form offset instead of character position.
   error finding frame source: invalid feature expression: "#.(UIOP/UTILITY:SYMBOL-TEST-TO-FEATURE-EXPRESSION (COMMON-LISP:QUOTE #:COMPILER-ERROR-CONTEXT-%SOURCE) (COMMON-LISP:QUOTE #:SB-C))"
   source: NIL
0]
```

I think, it is better to fix the root cause of the problem, not the readme file. Will try to find a solution soon.

**Comment by svetlyak40wt** [comment]
Also, interesting, that on CCL I have no this error. But I didn't noticed the problem, because SBCL was maked as "error allowed" in Travis config: https://github.com/40ants/weblocks/blob/e8b15e15c4f7b86157c35807bf56308b849dc510/.travis.yml#L34

But I disabled SBCL build because of other error during a travis build:

https://travis-ci.org/40ants/weblocks/jobs/464516040:

```
[package dissect]...[1/3] System 'rove' found. Loading the system..
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "DEBUG-SOURCE-FORM" not found in the SB-DI package.
;   
;       Line: 18, Column: 43, File-Position: 562
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/travis/build/40ants/weblocks/quicklisp/dists/dissect/software/dissect-fix-iteration-on-unknown-args/backend/sbcl.lisp" {10055D0143}>
Aborted during step [1/3].
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                          {10005205B3}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "dissect" "backend" "sbcl">
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10005205B3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {10055F5693}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {10055F5693}>)
2: (INVOKE-DEBUGGER #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {10055F5693}>)
3: (ERROR UIOP/LISP-BUILD:COMPILE-FILE-ERROR :CONTEXT-FORMAT "~/asdf-action::format-action/" :CONTEXT-ARGUMENTS ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "dissect" "backend" "sbcl">)))
4: (UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "dissect" "backend" "sbcl">)))
5: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "dissect" "backend" "sbcl">)
```

I think, I need to make SBCL a mandatory implementation where weblocks should work and to fix the both problems.

**Comment by svetlyak40wt** [comment]
@m00natic please, try again, this problem should be fixed by this commit: https://github.com/40ants/log4cl-json/commit/364e864cf0875211f9743a418024c6744e18c8fe

**Comment by m00natic** [comment]
Yes, sir, works fine now.  Thank you!

**Comment by svetlyak40wt** [comment]
Great!

**Pull request closed without merging**
